// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUZPR9rOzQjjOPNEhmh2UYDXvZ1UARZSc',
    appId: '1:242972939809:web:e8cd4ec5894ba491b57560',
    messagingSenderId: '242972939809',
    projectId: 'thriftify-1a971',
    authDomain: 'thriftify-1a971.firebaseapp.com',
    storageBucket: 'thriftify-1a971.firebasestorage.app',
    measurementId: 'G-8NZG91T9B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsXbWUSMpUZaX0HJGwDst2JRheFPlPvnI',
    appId: '1:242972939809:android:4b8b36e3f0867c97b57560',
    messagingSenderId: '242972939809',
    projectId: 'thriftify-1a971',
    storageBucket: 'thriftify-1a971.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzSUmOzaP-5dC6NN41Duc9xlKisd6Kmcs',
    appId: '1:242972939809:ios:e78a0bc760a3380ab57560',
    messagingSenderId: '242972939809',
    projectId: 'thriftify-1a971',
    storageBucket: 'thriftify-1a971.firebasestorage.app',
    iosClientId: '242972939809-80giaqa8gu14msoqnet1ejc3pa549m1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.thriftifyFyp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzSUmOzaP-5dC6NN41Duc9xlKisd6Kmcs',
    appId: '1:242972939809:ios:e78a0bc760a3380ab57560',
    messagingSenderId: '242972939809',
    projectId: 'thriftify-1a971',
    storageBucket: 'thriftify-1a971.firebasestorage.app',
    iosClientId: '242972939809-80giaqa8gu14msoqnet1ejc3pa549m1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.thriftifyFyp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUZPR9rOzQjjOPNEhmh2UYDXvZ1UARZSc',
    appId: '1:242972939809:web:a60c5215be73f6aab57560',
    messagingSenderId: '242972939809',
    projectId: 'thriftify-1a971',
    authDomain: 'thriftify-1a971.firebaseapp.com',
    storageBucket: 'thriftify-1a971.firebasestorage.app',
    measurementId: 'G-JLX42XF4EV',
  );

}